version: '3'
services:
  databse:
    image: mysql:8
    container_name: 'db-modular-monolith-test'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./docker/config/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
    ports:
      - "3306:3306"
  web:
    image: nginx
    container_name: 'web-modular-monolith-test'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/data/var/log/nginx:/var/log/nginx
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    environment:
      - NGINX_HOST=modular-monolith-test.loc
      - NGINX_PORT=80
  php:
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    container_name: 'php-modular-monolith-test'
    volumes:
      - ./:/var/www/html
      - ./docker/config/fpm/conf.d:/usr/local/etc/php/conf.d
